[target.'aarch64-unknown-linux-gnu']
linker = "/usr/local/bin/ld.mold"
rustflags = ["-C", "link-args=-L/usr/lib/aarch64-linux-gnu"]

[target.'x86_64-unknown-linux-gnu']
linker = "/usr/local/bin/ld.mold"
rustflags = ["-C", "link-args=-L/usr/lib/x86_64-linux-gnu"]

[target.'i686-unknown-linux-gnu']
linker = "/usr/local/bin/ld.mold"
rustflags = ["-C", "link-args=-L/usr/lib/i386-linux-gnu"]

[target.'armv7-unknown-linux-gnueabihf']
linker = "/usr/local/bin/ld.mold"
rustflags = ["-C", "link-args=-L/usr/lib/arm-linux-gnueabihf"]

[target.'aarch64-unknown-linux-musl']
linker = "/usr/local/bin/ld.mold"
rustflags = ["-C", "link-args=-L/usr/lib/aarch64-linux-musl"]

[target.'x86_64-unknown-linux-musl']
linker = "/usr/local/bin/ld.mold"
rustflags = ["-C", "link-args=-L/usr/lib/x86_64-linux-musl"]