#let name = ""
#let club = ""
#let age_group = ""

#let zero_elem = ""
#let A_elem = ""
#let B_elem = ""
#let C_elem = ""
#let D_elem = ""
#let E_elem = ""

#let abbr_1 = ""
#let desc_1 = ""
#let sgs_1 = ""
#let diff_1 = ""

#let abbr_2 = ""
#let desc_2 = ""
#let sgs_2 = ""
#let diff_2 = ""

#let abbr_3 = ""
#let desc_3 = ""
#let sgs_3 = ""
#let diff_3 = ""

#let abbr_4 = ""
#let desc_4 = ""
#let sgs_4 = ""
#let diff_4 = ""

#let abbr_5 = ""
#let desc_5 = ""
#let sgs_5 = ""
#let diff_5 = ""

#let abbr_6 = ""
#let desc_6 = ""
#let sgs_6 = ""
#let diff_6 = ""

#let abbr_7 = ""
#let desc_7 = ""
#let sgs_7 = ""
#let diff_7 = ""

#let abbr_8 = ""
#let desc_8 = ""
#let sgs_8 = ""
#let diff_8 = ""

#let abbr_9 = ""
#let desc_9 = ""
#let sgs_9 = ""
#let diff_9 = ""

#let abbr_10 = ""
#let desc_10 = ""
#let sgs_10 = ""
#let diff_10 = ""

#let abbr_11 = ""
#let desc_11 = ""
#let sgs_11 = ""
#let diff_11 = ""

#let abbr_12 = ""
#let desc_12 = ""
#let sgs_12 = ""
#let diff_12 = ""

#let abbr_abg = ""
#let desc_abg = ""
#let sgs_abg = ""
#let diff_abg = ""

#let sg_1 = ""
#let sg_2 = ""
#let sg_3 = ""
#let sg_4 = ""
#let sg_5 = ""
#let sg_6 = ""
#let sg_7 = ""
#let sg_8 = ""
#let sg_9 = ""
#let sg_10 = ""
#let sg_11 = ""
#let sg_12 = ""
#let sg_13 = ""
#let sg_14 = ""
#let sg_15 = ""
#let sg_16 = ""
#let sg_17 = ""

#let sum_diff = ""